import { NextRequest, NextResponse } from 'next/server'
import { groqChat, safeErrorMessage, parseGroqJson } from '@/lib/groq'
import { checkRateLimit, getClientIp } from '@/lib/rateLimit'

const MAX_TEXT_LEN = 20_000

// Single-pass escape — avoids double-escaping from chained replaces
const ESC_MAP: Record<string, string> = {
  '\\': '\\textbackslash{}',
  '&': '\\&',
  '%': '\\%',
  $: '\\$',
  '#': '\\#',
  _: '\\_',
  '{': '\\{',
  '}': '\\}',
  '~': '\\textasciitilde{}',
  '^': '\\textasciicircum{}',
}
function esc(s: string): string {
  return String(s).replace(/[\\&%$#_{}~^]/g, c => ESC_MAP[c] ?? c)
}

// URLs inside \href{} only need backslash + % escaped
function escUrl(url: string): string {
  return String(url).replace(/\\/g, '\\textbackslash{}').replace(/%/g, '\\%')
}

function generateLatex(d: any): string {
  const skillLines = (d.skills || [])
    .map((s: any) => `      \\textbf{${esc(s.category)}}{: ${esc(s.items)}} \\\\`)
    .join('\n')

  const experienceBlocks = (d.experience || []).map((exp: any) => `
    \\resumeSubheading
      {${esc(exp.company)}}{${esc(exp.dates)}}
      {${esc(exp.role)}}{${esc(exp.location)}}
      \\resumeItemListStart
${(exp.bullets || []).map((b: string) => `        \\resumeItem{${esc(b)}}`).join('\n')}
      \\resumeItemListEnd`).join('\n')

  const projectBlocks = (d.projects || []).map((p: any) => `
      \\resumeProjectHeading
        {\\textbf{${esc(p.name)}}${p.company ? ` $|$ \\textit{${esc(p.company)}}` : ''}${p.stack ? ` $|$ \\texttt{${esc(p.stack)}}` : ''}}{}
          \\resumeItemListStart
${(p.bullets || []).map((b: string) => `            \\resumeItem{${esc(b)}}`).join('\n')}
          \\resumeItemListEnd`).join('\n')

  const educationBlocks = (d.education || []).map((e: any) => `
    \\educationSubheading
      {${esc(e.school)}}{${esc(e.location)}}
      {${esc(e.degree)}}{${esc(e.dates)}}`).join('\n')

  const linkedinDisplay = d.linkedin?.display || d.linkedin?.url || ''
  const linkedinUrl = d.linkedin?.url || ''
  const portfolioDisplay = d.portfolio?.display || ''
  const portfolioUrl = d.portfolio?.url || ''

  return `%-------------------------
% ATS-Optimized Resume — Generated by ATSOptimizer
% Template: Jake Gutierrez (MIT License)
%------------------------
\\documentclass[10pt,letterpaper]{article}
\\usepackage[english]{babel}
\\usepackage[T1]{fontenc}
\\usepackage[empty]{fullpage}
\\usepackage{titlesec}
\\usepackage{marvosym}
\\usepackage[usenames,dvipsnames]{color}
\\usepackage{verbatim}
\\usepackage{enumitem}
\\usepackage[hidelinks]{hyperref}
\\usepackage{fancyhdr}
\\usepackage{tabularx}
\\input{glyphtounicode}
\\usepackage{anyfontsize}

\\pagestyle{fancy}
\\fancyhf{}
\\fancyfoot{}
\\setlength{\\footskip}{5pt}
\\renewcommand{\\headrulewidth}{0pt}
\\renewcommand{\\footrulewidth}{0pt}

\\addtolength{\\oddsidemargin}{-0.75in}
\\addtolength{\\evensidemargin}{-0.75in}
\\addtolength{\\textwidth}{1.5in}
\\addtolength{\\topmargin}{-1.0in}
\\addtolength{\\textheight}{2.0in}

\\urlstyle{same}
\\raggedbottom
\\raggedright
\\setlength{\\tabcolsep}{0in}

\\titleformat{\\section}{
  \\vspace{-6pt}\\scshape\\raggedright\\small
}{}{0em}{}[\\color{black}\\titlerule \\vspace{-5pt}]

\\pdfgentounicode=1

\\newcommand{\\resumeItem}[1]{\\item\\small{{#1 \\vspace{-3pt}}}}
\\newcommand{\\educationSubheading}[4]{
  \\vspace{-2pt}\\item
    \\begin{tabular*}{0.97\\textwidth}[t]{l@{\\extracolsep{\\fill}}r}
      \\textbf{#1} & #2 \\\\
      \\textit{\\small#3} & \\textit{\\small #4} \\\\
    \\end{tabular*}\\vspace{-7pt}
}
\\newcommand{\\resumeSubheading}[4]{
  \\vspace{-1pt}\\item
    \\begin{tabular*}{0.97\\textwidth}[t]{l@{\\extracolsep{\\fill}}r}
      \\textbf{\\small #1} $|$ \\texttt{\\small #3} $|$ \\texttt{\\small #4}  & \\textbf{\\small #2}
    \\end{tabular*}\\vspace{-1pt}
}
\\newcommand{\\resumeSubSubheading}[2]{
    \\item
    \\begin{tabular*}{0.97\\textwidth}{l@{\\extracolsep{\\fill}}r}
      \\textit{\\footnotesize #1} & \\textit{\\footnotesize #2} \\\\
    \\end{tabular*}\\vspace{-1pt}
}
\\newcommand{\\resumeProjectHeading}[2]{
    \\item
    \\begin{tabular*}{0.97\\textwidth}{l@{\\extracolsep{\\fill}}r}
      \\footnotesize #1 &  #2 \\\\
    \\end{tabular*}\\vspace{-7pt}
}
\\newcommand{\\resumeSubItem}[1]{\\resumeItem{#1}\\vspace{-4pt}}
\\renewcommand\\labelitemii{$\\vcenter{\\hbox{\\tiny$\\bullet$}}$}
\\newcommand{\\resumeSubHeadingListStart}{\\begin{itemize}[leftmargin=0.15in, label={}]}
\\newcommand{\\resumeSubHeadingListEnd}{\\end{itemize}}
\\newcommand{\\resumeItemListStart}{\\begin{itemize}}
\\newcommand{\\resumeItemListEnd}{\\end{itemize}\\vspace{-6pt}}

\\begin{document}

%----------HEADING----------
\\begin{center}
    \\textbf{\\Large \\scshape ${esc(d.name)}} \\\\ \\vspace{1pt}
    \\small ${esc(d.phone)} $|$ \\href{mailto:${escUrl(d.email)}}{\\underline{${esc(d.email)}}}${linkedinUrl ? ` $|$\n    \\href{${escUrl(linkedinUrl)}}{\\underline{${esc(linkedinDisplay)}}}` : ''}${portfolioUrl ? ` $|$\n    \\href{${escUrl(portfolioUrl)}}{\\underline{${esc(portfolioDisplay)}}}` : ''} $|$ ${esc(d.location)}
\\end{center}

%----------PROFESSIONAL SUMMARY----------
\\section{Professional Summary}
 \\begin{itemize}[leftmargin=0.15in, label={}]
 \\small{\\item{
${esc(d.summary)}
 }}
 \\end{itemize}

%-----------TECHNICAL SKILLS-----------
\\section{Technical Skills}
 \\begin{itemize}[leftmargin=0.15in, label={}]
    \\small{\\item{
${skillLines}
    }}
 \\end{itemize}

%-----------EXPERIENCE-----------
\\section{Professional Experience}
  \\resumeSubHeadingListStart
${experienceBlocks}
  \\resumeSubHeadingListEnd

${(d.projects || []).length > 0 ? `%-----------PROJECTS-----------
\\section{Professional Projects}
    \\resumeSubHeadingListStart
${projectBlocks}
    \\resumeSubHeadingListEnd` : ''}

%-----------EDUCATION-----------
\\section{Education}
  \\resumeSubHeadingListStart
${educationBlocks}
  \\resumeSubHeadingListEnd

\\end{document}
`
}

export async function POST(req: NextRequest) {
  const ip = getClientIp(req)
  const { allowed, retryAfter } = checkRateLimit(ip)
  if (!allowed) {
    return NextResponse.json(
      { error: 'Too many requests. Please try again later.' },
      { status: 429, headers: { 'Retry-After': String(retryAfter) } }
    )
  }

  try {
    const body = await req.json()
    const { resumeText } = body

    if (typeof resumeText !== 'string' || resumeText.trim().length < 50) {
      return NextResponse.json({ error: 'Invalid resume text.' }, { status: 400 })
    }
    if (resumeText.length > MAX_TEXT_LEN) {
      return NextResponse.json({ error: 'Resume text is too large.' }, { status: 413 })
    }

    const extractPrompt = `Extract structured data from this resume text and return ONLY valid JSON — no markdown, no explanation.

RESUME:
${resumeText.slice(0, 5000)}

Return this exact JSON shape:
{
  "name": "Full Name",
  "phone": "phone number",
  "email": "email@example.com",
  "linkedin": { "url": "https://linkedin.com/in/...", "display": "linkedin.com/in/..." },
  "portfolio": { "url": "https://...", "display": "Portfolio" },
  "location": "City, Country",
  "summary": "Full professional summary paragraph",
  "skills": [
    { "category": "Languages", "items": "JavaScript, TypeScript, Python" },
    { "category": "Frameworks", "items": "React.js, Node.js" }
  ],
  "experience": [
    {
      "company": "Company Name",
      "role": "Job Title",
      "location": "City, Country",
      "dates": "Month Year -- Present",
      "bullets": ["Led team of 5...", "Built feature that..."]
    }
  ],
  "projects": [
    {
      "name": "Project Name",
      "company": "Company",
      "stack": "React.js, Node.js, MongoDB",
      "bullets": ["Built...", "Achieved..."]
    }
  ],
  "education": [
    {
      "school": "University Name",
      "location": "City, Country",
      "degree": "Bachelor of Technology in Computer Science",
      "dates": "2016 -- 2020"
    }
  ]
}`

    const raw = await groqChat([{ role: 'user', content: extractPrompt }], { max_tokens: 2000 })
    const structured = parseGroqJson(raw)

    if (!structured.name || !Array.isArray(structured.experience)) {
      throw new Error('Unexpected response format. Please try again.')
    }

    const texSource = generateLatex(structured)

    return new NextResponse(texSource, {
      headers: {
        'Content-Type': 'text/plain; charset=utf-8',
        'Content-Disposition': 'attachment; filename="optimized-resume.tex"',
      },
    })
  } catch (e: any) {
    console.error('LaTeX route error:', e)
    return NextResponse.json(
      { error: safeErrorMessage(e, 'Failed to generate LaTeX. Please try again.') },
      { status: 500 }
    )
  }
}
